"""Adds password to User model

Revision ID: 72fef209bc1c
Revises: e47756a67ec4
Create Date: 2024-04-26 14:27:18.983493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fef209bc1c'
down_revision = 'e47756a67ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.create_unique_constraint("unique_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
